epochs: 10

demo:
  param_group_1:
    param_1: 'a'
    param_2: 123
  param_group_2:
    param_1: 'b'
    param_2: 456

dataloader:
  _target_: torch.utils.data.DataLoader
  _partial_: true
  batch_size: 32
  shuffle: true
  num_workers: 0

model:
  _target_: ex_2.model.PolarSunNet

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
<<<<<<< HEAD
  lr: 5e-4
=======
  lr: 0.001
>>>>>>> 509be15 (started on competition)

defaults:
  - _self_
  - dataset: real_dataset
  - model/backbone: vanilla # resnet, vanilla
<<<<<<< HEAD
  - model/representation: DOP+AOP # raw, IQU, DOP+AOP, IQU+DOP+AOP
  - model/readout: vector # angle, vector
=======
  - model/representation: raw # raw, IQU, DOP+AOP, IQU+DOP+AOP
<<<<<<< HEAD
  - model/readout: vecotr # angle, vector
>>>>>>> 509be15 (started on competition)
=======
  - model/readout: vector # angle, vector
>>>>>>> 9cd4f2a (competition)
  # use mse loss when readout as angle, use l_norm loss when readout as vector
  - loss: l_norm # mse, l_norm
  - optional lr@optimizer: ${model/backbone}_${model/representation}_${model/readout}